service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  stage: dev
  profile: joshua
  httpApi:
    cors: true
functions:
  graphql:
    handler: functions/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-offline
